
# ----------------------------------------------------
# 2. MASTER MAPPING (YOUR FULL LIST)
# ----------------------------------------------------
MASTER_MAP = {
    "20MICRONS.NS": {"Name": "20 Microns Ltd.", "Sector": "Chemicals - Specialty"},
    "AARTIIND.NS": {"Name": "Aarti Industries", "Sector": "Chemicals - Specialty"},
    "ABB.NS": {"Name": "ABB India", "Sector": "Industrial - Electrical"},
    "ACC.NS": {"Name": "ACC", "Sector": "Construction - Cement"},
    "ACMESOLAR.NS": {"Name": "Acme Solar Holdings", "Sector": "Energy - Renewable"},
    "ADANIENSOL.NS": {"Name": "Adani Energy Solutions", "Sector": "Energy - T&D"},
    "ADANIENT.NS": {"Name": "Adani Enterprises Ltd.", "Sector": "Conglomerate"},
    "ADANIGREEN.NS": {"Name": "Adani Green Energy Ltd.", "Sector": "Energy - Renewable"},
    "ADANIPORTS.NS": {"Name": "Adani Ports & Special Economic Zone Ltd.", "Sector": "Infrastructure - Ports"},
    "ADANIPOWER.NS": {"Name": "Adani Power Ltd.", "Sector": "Energy - Power"},
    "ATGL.NS": {"Name": "Adani Total Gas", "Sector": "Energy - Gas Distribution"},
    "ABCAPITAL.NS": {"Name": "Aditya Birla Capital", "Sector": "Financials - Holding"},
    "ABFRL.NS": {"Name": "Aditya Birla Fashion and Retail Ltd.", "Sector": "Retail - Apparel"},
    "ABREL.NS": {"Name": "Aditya Birla Real Estates", "Sector": "Real Estate"},
    "AFCONS.NS": {"Name": "Afcons Infrastructure Ltd.", "Sector": "Construction - Infrastructure"},
    "AHLUCONT.NS": {"Name": "Ahluwalia Contracts (India) Ltd.", "Sector": "Construction"},
    "ALKYLAMINE.NS": {"Name": "Alkyl Amines Chemicals Ltd.", "Sector": "Chemicals - Specialty"},
    "ABDL.NS": {"Name": "Allied Blenders & Distillers", "Sector": "Consumer - Beverages (Alcoholic)"},
    "ADSL.NS": {"Name": "Allied Digital", "Sector": "Technology - Services"},
    "ARE&M.NS": {"Name": "Amara Raja Energy & Mobility", "Sector": "Automotive - Ancillaries (Batteries)"},
    "AMBER.NS": {"Name": "Amber Enterprises India Ltd", "Sector": "Consumer - Durables (EMS)"},
    "AMBUJACEM.NS": {"Name": "Ambuja Cements", "Sector": "Construction - Cement"},
    "ANANTRAJ.NS": {"Name": "Anant Raj", "Sector": "Real Estate"},
    "ACL.BO": {"Name": "Andhra Cements", "Sector": "Construction - Cement"},
    "ANGELONE.NS": {"Name": "Angel One", "Sector": "Financials - Stockbroking"},
    "APARINDS.NS": {"Name": "Apar Industries", "Sector": "Industrial - Capital Goods"},
    "APLAPOLLO.NS": {"Name": "APL Apollo Tubes", "Sector": "Metals - Steel Pipes"},
    "APOLLOHOSP.NS": {"Name": "Apollo Hospitals Enterprise Ltd.", "Sector": "Healthcare - Services"},
    "APOLLO.NS": {"Name": "Apollo Micro Systems", "Sector": "Defence - Electronics"},
    "APOLLOPIPE.NS": {"Name": "Apollo Pipes", "Sector": "Industrial - Plastics & Pipes"},
    "APOLLOTYRE.NS": {"Name": "Apollo Tyres", "Sector": "Automotive - Ancillaries"},
    "ARVINDFASN.NS": {"Name": "Arvind Fashions Ltd.", "Sector": "Retail - Apparel"},
    "ARVIND.NS": {"Name": "Arvind Ltd", "Sector": "Textiles"},
    "ASAHIINDIA.NS": {"Name": "Asahi India Glass Ltd.", "Sector": "Consumer - Glass"},
    "ASHOKLEY.NS": {"Name": "Ashok Leyland", "Sector": "Automotive"},
    "ASHOKA.NS": {"Name": "Ashoka Buildcon", "Sector": "Construction - Infrastructure"},
    "ASIANENE.NS": {"Name": "Asian Energy Services", "Sector": "Energy - Oil & Gas Services"},
    "ASIANHOTNR.NS": {"Name": "Asian Hotels (North) Ltd.", "Sector": "Hospitality"},
    "ASIANPAINT.NS": {"Name": "Asian Paints", "Sector": "Chemicals - Paints & Coatings"},
    "ASMTEC.BO": {"Name": "ASM Technologies Ltd", "Sector": "Technology - Semiconductor Services"},
    "ASTRAMICRO.NS": {"Name": "Astra Microwave Products Ltd", "Sector": "Defence - Aerospace"},
    "ASTRAL.NS": {"Name": "Astral Ltd", "Sector": "Industrial - Plastics & Pipes"},
    "ATULAUTO.NS": {"Name": "Atul Auto", "Sector": "Automotive"},
    "ATUL.NS": {"Name": "Atul Ltd", "Sector": "Chemicals - Specialty"},
    "AURIONPRO.NS": {"Name": "Aurionpro Solutions", "Sector": "Technology - Services (Fintech)"},
    "AUROPHARMA.NS": {"Name": "Aurobindo Pharma", "Sector": "Pharma"},
    "AUTOIND.NS": {"Name": "Autoline Industries", "Sector": "Automotive - Ancillaries"},
    "AVANTEL.NS": {"Name": "Avantel Ltd.", "Sector": "Technology - Communications"},
    "AVANTIFEED.NS": {"Name": "Avanti Feeds", "Sector": "Consumer - Aquaculture"},
    "AWFIS.NS": {"Name": "AWFIS", "Sector": "Real Estate - Services"},
    "AXISBANK.NS": {"Name": "Axis Bank", "Sector": "Financials - Banking"},
    "BAJAJ-AUTO.NS": {"Name": "Bajaj Auto", "Sector": "Automotive"},
    "BAJAJCON.NS": {"Name": "Bajaj Consumer Care Ltd.", "Sector": "Consumer - Personal Care"},
    "BAJAJFINSV.NS": {"Name": "Bajaj Finserv", "Sector": "Financials - NBFC"},
    "BAJFINANCE.NS": {"Name": "Bajaj Finance", "Sector": "Financials - NBFC"},
    "BAJAJST.BO": {"Name": "Bajaj Steel Inds. Ltd.", "Sector": "Metals - Steel"},
    "BALAMINES.NS": {"Name": "Balaji Amines", "Sector": "Chemicals - Specialty"},
    "BALRAMCHIN.NS": {"Name": "Balrampur Chini Mills Ltd.", "Sector": "Consumer - Sugar"},
    "BANCOINDIA.NS": {"Name": "Banco Products (India) Ltd.", "Sector": "Automotive - Ancillaries"},
    "BANDHANBNK.NS": {"Name": "Bandhan Bank", "Sector": "Financials - Banking"},
    "BANKBARODA.NS": {"Name": "Bank of Baroda", "Sector": "Financials - Banking"},
    "BEEKAY.BO": {"Name": "Beekay Steel Industries Ltd.", "Sector": "Metals - Steel"},
    "BEL.NS": {"Name": "BEL (Bharat Electronics)", "Sector": "Defence - Aerospace"},
    "BEML.NS": {"Name": "BEML", "Sector": "Defence - Heavy Engineering"},
    "BERGEPAINT.NS": {"Name": "Berger Paints", "Sector": "Chemicals - Paints & Coatings"},
    "BDL.NS": {"Name": "Bharat Dynamics", "Sector": "Defence - Aerospace"},
    "BHARATFORG.NS": {"Name": "Bharat Forge Ltd", "Sector": "Defence - Ancillaries"},
    "BHARTIARTL.NS": {"Name": "Bharti Airtel Ltd.", "Sector": "Telecom"},
    "BHARTIHEXA.NS": {"Name": "Bharti Hexacom", "Sector": "Telecom"},
    "BHEL.NS": {"Name": "BHEL", "Sector": "Industrial - Heavy Electrical"},
    "BIOCON.NS": {"Name": "Biocon", "Sector": "Pharma - Biotech"},
    "BIRLACORPN.NS": {"Name": "Birla Corpn.", "Sector": "Construction - Cement"},
    "BSOFT.NS": {"Name": "Birlasoft Ltd", "Sector": "Technology - Services"},
    "BBOX.NS": {"Name": "Black Box Ltd.", "Sector": "Technology - Services (Networking)"},
    "BOROLTD.NS": {"Name": "Borosil Ltd", "Sector": "Consumer - Glass"},
    "BORORENEW.NS": {"Name": "Borosil Renewables Ltd.", "Sector": "Energy - Renewable"},
    "BRIGADE.NS": {"Name": "Brigade Enterprises", "Sector": "Real Estate"},
    "BIRET.NS": {"Name": "Brookfield India Real Estate Trust", "Sector": "Real Estate - REIT"},
    "BSE.NS": {"Name": "BSE Ltd", "Sector": "Financials - Exchange"},
    "MAPMYINDIA.NS": {"Name": "C.E. Info Systems Ltd.", "Sector": "Technology - Services (GIS)"},
    "CAMS.NS": {"Name": "CAMS", "Sector": "Financials - Asset Management Services"},
    "CAPLIPOINT.NS": {"Name": "Caplin Point Laboratories", "Sector": "Pharma"},
    "CARRARO.NS": {"Name": "Carraro India Ltd.", "Sector": "Automotive - Ancillaries"},
    "CARYSIL.NS": {"Name": "Carysil", "Sector": "Consumer - Durables"},
    "CDSL.NS": {"Name": "CDSL", "Sector": "Financials - Depository"},
    "CERA.NS": {"Name": "Cera Sanitaryware Ltd.", "Sector": "Consumer - Durables"},
    "CFF.BO": {"Name": "CFF Fluid Control Ltd", "Sector": "Defence"},
    "CGPOWER.NS": {"Name": "CG Power and Industrial Solutions", "Sector": "Industrial - Electrical (Semiconductor)"},
    "CHALET.NS": {"Name": "Chalet Hotels", "Sector": "Hospitality"},
    "CHAMBLFERT.NS": {"Name": "Chambal Fertilisers & Chemicals Ltd.", "Sector": "Chemicals - Fertilizers"},
    "CHEMPLASTS.NS": {"Name": "Chemplast Sanmar Ltd", "Sector": "Chemicals - Specialty"},
    "CHOLAHLDNG.NS": {"Name": "Cholamandalam Financial Holdings Ltd.", "Sector": "Financials - Holding"},
    "CHOLAFIN.NS": {"Name": "Cholamandalam Investment & Finance Company Ltd.", "Sector": "Financials - NBFC"},
    "CIEINDIA.NS": {"Name": "CIE Automotive India Ltd.", "Sector": "Automotive - Ancillaries"},
    "CIPLA.NS": {"Name": "Cipla", "Sector": "Pharma"},
    "CUB.NS": {"Name": "City Union Bank", "Sector": "Financials - Banking"},
    "COALINDIA.NS": {"Name": "Coal India", "Sector": "Metals - Mining"},
    "COCHINSHIP.NS": {"Name": "Cochin Shipyard", "Sector": "Defence - Shipbuilding"},
    "COFORGE.NS": {"Name": "Coforge", "Sector": "Technology - Services"},
    "CONCOR.NS": {"Name": "Container Corporation of India Ltd.", "Sector": "Logistics"},
    "COROMANDEL.NS": {"Name": "Coromandel International", "Sector": "Chemicals - Fertilizers"},
    "CRAFTSMAN.NS": {"Name": "Craftsman Automation Ltd.", "Sector": "Industrial - Capital Goods (Auto)"},
    "CYIENTDLM.NS": {"Name": "Cyient DLM", "Sector": "Industrial - EMS"},
    "DPWIRES.NS": {"Name": "D P Wires", "Sector": "Metals - Steel"},
    "DABUR.NS": {"Name": "Dabur India", "Sector": "Consumer - Health"},
    "DATAPATTNS.NS": {"Name": "Data Patterns (India) Ltd.", "Sector": "Defence - Aerospace"},
    "DCXINDIA.BO": {"Name": "DCX Systems Limited", "Sector": "Industrial - EMS"},
    "DEEDEV.NS": {"Name": "Dee Development Engineers", "Sector": "Industrial - Engineering"},
    "DEEPAKFERT.NS": {"Name": "Deepak Fertilisers & Petrochemicals Corporation Ltd.", "Sector": "Chemicals - Fertilizers"},
    "DEEPAKNTR.NS": {"Name": "Deepak Nitrate", "Sector": "Chemicals - Specialty"},
    "DELHIVERY.NS": {"Name": "Delhivery", "Sector": "Logistics"},
    "DEVYANI.NS": {"Name": "Devyani International", "Sector": "Retail - QSR"},
    "DHABRIYA.BO": {"Name": "Dhabriya Polywood Ltd.", "Sector": "Industrial - Plastics & Polymers"},
    "DHAMPURSUG.NS": {"Name": "Dhampur Sugar Mills Ltd.", "Sector": "Consumer - Sugar"},
    "DBL.NS": {"Name": "Dilip Buildcon Ltd.", "Sector": "Construction - Infrastructure"},
    "DIVISLAB.NS": {"Name": "Divi's Laboratories Ltd.", "Sector": "Pharma - APIs"},
    "DIXON.NS": {"Name": "Dixon Technologies (India) Ltd.", "Sector": "Industrial - EMS"},
    "DLF.NS": {"Name": "DLF", "Sector": "Real Estate"},
    "DYNAMATECH.NS": {"Name": "Dynamatic Technologies Ltd.", "Sector": "Defence - Ancillaries"},
    "E2E.NS": {"Name": "E2E Networks Ltd", "Sector": "Technology - Services (Cloud)"},
    "EASEMYTRIP.NS": {"Name": "Easy Trip Planners", "Sector": "Travel - Services"},
    "EICHERMOT.NS": {"Name": "Eicher Motors", "Sector": "Automotive"},
    "EIHOTEL.NS": {"Name": "EIH Ltd", "Sector": "Hospitality"},
    "EKI.BO": {"Name": "EKI Energy Services Ltd.", "Sector": "Industrial - Environmental Services"},
    "EMAMILTD.NS": {"Name": "Emami Ltd", "Sector": "Consumer - Goods"},
    "EMBASSY.NS": {"Name": "Embassy Office Parks REIT", "Sector": "Real Estate - REIT"},
    "EMKAY.NS": {"Name": "Emkay Global", "Sector": "Financials - Stockbroking"},
    "EMUDHRA.NS": {"Name": "eMudhra Ltd.", "Sector": "Technology - Services (Security)"},
    "IBREALEST.NS": {"Name": "Equinox India Developments", "Sector": "Real Estate"},
    "EQUITASBNK.NS": {"Name": "Equitas Small Finance Bank Ltd.", "Sector": "Financials - Banking"},
    "ESSARSHPNG.NS": {"Name": "Essar Shipping", "Sector": "Transport - Shipping"},
    "ETERNAL.NS": {"Name": "Eternal", "Sector": "Consumer - E-commerce"},
    "EVEREADY.NS": {"Name": "Eveready Industries India Ltd.", "Sector": "Consumer - Durables"},
    "EKC.NS": {"Name": "Everest Kanto Cylinder", "Sector": "Industrial - Capital Goods"},
    "EXPLEOSOL.NS": {"Name": "Expleo Solutions", "Sector": "Technology - Services"},
    "FAZE3Q.NS": {"Name": "Faze Three Ltd.", "Sector": "Textiles"},
    "FEDERALBNK.NS": {"Name": "Federal Bank", "Sector": "Financials - Banking"},
    "FIEMIND.NS": {"Name": "Fiem Industries", "Sector": "Automotive - Ancillaries"},
    "FINEORG.NS": {"Name": "Fine Organic", "Sector": "Chemicals - Specialty"},
    "FCL.NS": {"Name": "Fineotex Chemical Ltd.", "Sector": "Chemicals - Specialty"},
    "FINCABLES.NS": {"Name": "Finolex Cables", "Sector": "Industrial - Cables"},
    "FINPIPE.NS": {"Name": "Finolex Inds.", "Sector": "Industrial - Plastics & Pipes"},
    "FIVESTAR.NS": {"Name": "Five Star Business Finance", "Sector": "Financials - NBFC"},
    "NYKAA.NS": {"Name": "FSN E Commerce Ventures (Nykaa)", "Sector": "Consumer - E-commerce"},
    "OLAELEC.BO": {"Name": "Ola Electric Mobility Ltd.", "Sector": "Automotive - EVs"},
    "GAIL.NS": {"Name": "GAIL (India)", "Sector": "Energy - Oil & Gas"},
    "GALXBRG.BO": {"Name": "Galaxy Bearings Ltd.", "Sector": "Automotive - Ancillaries (Industrial)"},
    "GRSE.NS": {"Name": "Garden Reach Shipbuilders & Engineers Ltd.", "Sector": "Defence - Shipbuilding"},
    "GARUDA.NS": {"Name": "Garuda Construction", "Sector": "Real Estate"},
    "GLAND.NS": {"Name": "Gland Pharma", "Sector": "Pharma"},
    "GLENMARK.NS": {"Name": "Glenmark Pharma.", "Sector": "Pharma"},
    "GLOBUSSPR.NS": {"Name": "Globus Spirits", "Sector": "Consumer - Beverages (Alcoholic)"},
    "GMRP&UI.NS": {"Name": "GMR Power and Urban Infra", "Sector": "Infrastructure - Power"},
    "GPIL.NS": {"Name": "Godawari Power & Ispat Ltd.", "Sector": "Metals - Steel"},
    "GODREJAGRO.NS": {"Name": "Godrej Agrovet", "Sector": "Consumer - Agribusiness"},
    "GODREJCP.NS": {"Name": "Godrej Consumer Products Ltd.", "Sector": "Consumer - Personal Care"},
    "GODREJPROP.NS": {"Name": "Godrej Properties", "Sector": "Real Estate"},
    "GOKEX.NS": {"Name": "Gokaldas Exports", "Sector": "Textiles - Apparel"},
    "GRANULES.NS": {"Name": "Granules India Ltd.", "Sector": "Pharma"},
    "GRAPHITE.NS": {"Name": "Graphite India", "Sector": "Metals - Graphite Electrodes"},
    "GRASIM.NS": {"Name": "Grasim Inds", "Sector": "Conglomerate"},
    "GREENLAM.NS": {"Name": "Greenlam Industries", "Sector": "Industrial - Wood Products"},
    "GREENPANEL.NS": {"Name": "Greenpanel Inds.", "Sector": "Industrial - Wood Products"},
    "GREENPLY.NS": {"Name": "Greenply Inds.", "Sector": "Industrial - Wood Products"},
    "GVT&D.NS": {"Name": "GE Vernova T&D India", "Sector": "Energy - T&D", "AddedDate": "2026-06-04"},
    "FLUOROCHEM.NS": {"Name": "Gujarat Fluoroch", "Sector": "Chemicals - Specialty"},
    "HAL.NS": {"Name": "HAL (Hindustan Aeronautics Ltd.)", "Sector": "Defence - Aerospace"},
    "HATHWAY.NS": {"Name": "Hathway Cable & Datacom Ltd.", "Sector": "Telecom - Broadband"},
    "HAVELLS.NS": {"Name": "Havells India Ltd", "Sector": "Consumer - Durables (Electrical)"},
    "HCLTECH.NS": {"Name": "HCL Technologies", "Sector": "Technology - Services"},
    "HDFCAMC.NS": {"Name": "HDFC Asset Management Company Ltd.", "Sector": "Financials - Asset Management"},
    "HDFCBANK.NS": {"Name": "HDFC Bank", "Sector": "Financials - Banking"},
    "HDFCLIFE.NS": {"Name": "HDFC Life Insurance Company Ltd.", "Sector": "Financials - Insurance"},
    "HEMIPROP.NS": {"Name": "Hemisphere Properties", "Sector": "Real Estate"},
    "HGINFRA.NS": {"Name": "HG Infra", "Sector": "Construction - Infrastructure"},
    "HITECH.NS": {"Name": "Hi-tech Pipes", "Sector": "Industrial - Electrical"},
    "HIGHENE.BO": {"Name": "High Energy Batteries (India) Ltd", "Sector": "Metals - Steel Pipes"},
    "HIRECT.NS": {"Name": "Hind Rectifiers Ltd.", "Sector": "Defence"},
    "HINDALCO.NS": {"Name": "Hindalco", "Sector": "Industrial - Electrical"},
    "HINDCOPPER.NS": {"Name": "Hindustan Copper", "Sector": "Metals - Non-ferrous"},
    "HINDPETRO.NS": {"Name": "Hindustan Petroleum Corporation Ltd.", "Sector": "Metals - Non-ferrous"},
    "HINDUNILVR.NS": {"Name": "Hindustan Unilever", "Sector": "Energy - Oil & Gas"},
    "HINDZINC.NS": {"Name": "Hindustan Zinc", "Sector": "Consumer - FMCG"},
    "POWERINDIA.NS": {"Name": "Hitachi Energy India Ltd", "Sector": "Metals - Non-ferrous"},
    "HUDCO.NS": {"Name": "HUDCO", "Sector": "Financials - Housing Finance"},
    "ICICIBANK.NS": {"Name": "ICICI Bank", "Sector": "Financials - Banking"},
    "ICICIGI.NS": {"Name": "ICICI Lombard General Insurance Company Ltd.", "Sector": "Financials - Insurance"},
    "ICICIPRULI.NS": {"Name": "ICICI Prudential Life Insurance Company Ltd.", "Sector": "Financials - Insurance"},
    "IDFCFIRSTB.NS": {"Name": "IDFC First Bank", "Sector": "Financials - Banking"},
    "IEX.NS": {"Name": "IEX (Indian Energy Exchange)", "Sector": "Financials - Exchange"},
    "IFCI.NS": {"Name": "IFCI Ltd", "Sector": "Financials - NBFC"},
    "IIFL.NS": {"Name": "IIFL Finance", "Sector": "Financials - NBFC"},
    "INDIAGLYCO.NS": {"Name": "India Glycol", "Sector": "Chemicals - Specialty"},
    "IPL.NS": {"Name": "India Pesticides Limited", "Sector": "Chemicals - Agrochemicals"},
    "INDHOTEL.NS": {"Name": "Indian Hotels Company Ltd", "Sector": "Hospitality"},
    "INDIANHUME.NS": {"Name": "Indian Hume Pipe", "Sector": "Construction - Pipes"},
    "IOC.NS": {"Name": "Indian Oil Corporation Ltd.", "Sector": "Energy - Oil & Gas"},
    "IRCTC.NS": {"Name": "Indian Railway Catering & Tourism Corporation Ltd.", "Sector": "Travel - Railway Services"},
    "IRFC.NS": {"Name": "Indian Railway Finance Corporation Ltd.", "Sector": "Financials - NBFC"},
    "IREDA.NS": {"Name": "Indian Renewable Energy Development Agency Ltd", "Sector": "Financials - NBFC"},
    "INDIGOPNTS.NS": {"Name": "Indigo Paints", "Sector": "Chemicals - Paints"},
    "INDUSTOWER.NS": {"Name": "Indus Towers", "Sector": "Telecom - Tower Infrastructure"},
    "INDUSINDBK.NS": {"Name": "IndusInd Bank", "Sector": "Financials - Banking"},
    "INFY.NS": {"Name": "Infosys", "Sector": "Technology - Services"},
    "INOXGREEN.NS": {"Name": "Inox Green Energy Services Ltd.", "Sector": "Energy - Renewable Services"},
    "INOXWIND.NS": {"Name": "Inox Wind", "Sector": "Energy - Renewable"},
    "INSECTICID.NS": {"Name": "Insecticides (India)", "Sector": "Chemicals - Agrochemicals"},
    "INDIGO.NS": {"Name": "Interglobe Aviation Ltd. (Indigo)", "Sector": "Transport - Airlines"},
    "INTLCONV.NS": {"Name": "International Conveyors Ltd.", "Sector": "Industrial - Engineering"},
    "IRB.NS": {"Name": "IRB Infrastructure Developers Ltd", "Sector": "Construction - Infrastructure"},
    "IRIS.NS": {"Name": "Iris Business Services Ltd.", "Sector": "Technology - Services (Cloud)"},
    "ITCHOTELS.NS": {"Name": "ITC Hotels", "Sector": "Hospitality"},
    "ITC.NS": {"Name": "ITC Ltd", "Sector": "Consumer - Tobacco & FMCG"},
    "JAIBALAJI.NS": {"Name": "Jai Balaji Inds.", "Sector": "Metals - Steel"},
    "JPPOWER.NS": {"Name": "Jaiprakash Power Ventures Ltd.", "Sector": "Energy - Power"},
    "JAYKAY.NS": {"Name": "Jaykay Enterprises Ltd.", "Sector": "Defence - Aerospace"},
    "JINDALSAW.NS": {"Name": "Jindal Saw", "Sector": "Metals - Steel Pipes"},
    "JSL.NS": {"Name": "Jindal Stainless Ltd.", "Sector": "Metals - Steel"},
    "JINDALSTEL.NS": {"Name": "Jindal Steel & Power Ltd.", "Sector": "Metals - Steel"},
    "JIOFIN.NS": {"Name": "JIO Financial Services", "Sector": "Financials - NBFC/Fintech"},
    "JKLAKSHMI.NS": {"Name": "JK Lakshmi Cem.", "Sector": "Construction - Cement"},
    "JKPAPER.NS": {"Name": "JK Paper", "Sector": "Paper"},
    "JKTYRE.NS": {"Name": "JK Tyre & Indust", "Sector": "Automotive - Ancillaries"},
    "JSWENERGY.NS": {"Name": "JSW Energy", "Sector": "Energy - Utilities"},
    "JSWINFRA.NS": {"Name": "JSW Infrastructure", "Sector": "Logistics - Ports"},
    "JSWSTEEL.NS": {"Name": "JSW Steel", "Sector": "Metals - Steel"},
    "JTLIND.NS": {"Name": "JTL Industries Ltd.", "Sector": "Metals - Steel Pipes"},
    "JUBLFOOD.NS": {"Name": "Jubilant FoodWorks Ltd.", "Sector": "Retail - QSR"},
    "JUBLPHARMA.NS": {"Name": "Jubilant Pharmova", "Sector": "Pharma"},
    "JWL.NS": {"Name": "Jupiter Wagons", "Sector": "Industrial - Railway Equipment"},
    "KAJARIACER.NS": {"Name": "Kajaria Ceramics", "Sector": "Construction - Materials"},
    "KPIL.NS": {"Name": "Kalpataru Projects International Ltd.", "Sector": "Construction - Infrastructure"},
    "KALYANKJIL.NS": {"Name": "Kalyan Jewellers", "Sector": "Retail - Jewellery"},
    "KANSAINER.NS": {"Name": "Kansai Nerolac", "Sector": "Chemicals - Paints & Coatings"},
    "KSCL.NS": {"Name": "Kaveri Seed Co.", "Sector": "Consumer - Agribusiness"},
    "KAYNES.NS": {"Name": "Kaynes Technology India Ltd", "Sector": "Industrial - EMS"},
    "KEI.NS": {"Name": "KEI Industries", "Sector": "Industrial - Cables"},
    "KHAICHEM.NS": {"Name": "Khaitan Chemical & Fertilizers Ltd.", "Sector": "Chemicals - Fertilizers"},
    "KLBRENG-B.BO": {"Name": "Kilburn Engineering Ltd.", "Sector": "Industrial - Engineering"},
    "KIRLOSENG.NS": {"Name": "Kirloskar Oil Engines", "Sector": "Industrial - Engineering"},
    "KOTAKBANK.NS": {"Name": "Kotak Mahindra Bank", "Sector": "Financials - Banking"},
    "KPIGREEN.NS": {"Name": "KPI Green Energy Ltd.", "Sector": "Energy - Renewable"},
    "KPITTECH.NS": {"Name": "KPIT Technologies Ltd", "Sector": "Technology - R&D"},
    "KPRMILL.NS": {"Name": "KPR Mill", "Sector": "Textiles - Apparel"},
    "LTF.NS": {"Name": "L&T Fin.Holdings", "Sector": "Financials - NBFC"},
    "LTTS.NS": {"Name": "L&T Technology Services Ltd.", "Sector": "Technology - R&D"},
    "LAOPALA.NS": {"Name": "La Opala RG Ltd", "Sector": "Consumer - Glassware"},
    "LAHOTIOV.BO": {"Name": "Lahoti Overseas Ltd.", "Sector": "Textiles"},
    "LT.NS": {"Name": "Larsen & Toubro Ltd.", "Sector": "Conglomerate - Engineering"},
    "LAURUSLABS.NS": {"Name": "Laurus Labs", "Sector": "Pharma - APIs"},
    "LEMONTREE.NS": {"Name": "Lemon Tree Hotel", "Sector": "Hospitality"},
    "LICI.NS": {"Name": "Life Insurance Corporation", "Sector": "Financials - Insurance"},
    "LINCOLN.NS": {"Name": "Lincoln Pharma.", "Sector": "Pharma"},
    "LLOYDSME.NS": {"Name": "Lloyds Metals & Energy Ltd.", "Sector": "Metals - Steel"},
    "LOTUSCHO.BO": {"Name": "Lotus Developers", "Sector": "Real Estate"},
    "LUMAXTECH.NS": {"Name": "Lumax Auto Tech", "Sector": "Automotive - Ancillaries"},
    "LUMAXIND.NS": {"Name": "Lumax Industries", "Sector": "Automotive - Ancillaries"},
    "LUPIN.NS": {"Name": "Lupin", "Sector": "Pharma"},
    "LYKALABS.NS": {"Name": "Lyka Labs", "Sector": "Pharma"},
    "M&M.NS": {"Name": "M & M (Mahindra & Mahindra Ltd.)", "Sector": "Automotive"},
    "MACPOWER.NS": {"Name": "MacPower CNC Machines", "Sector": "Industrial - Capital Goods"},
    "LODHA.NS": {"Name": "Macrotech Developers Ltd. (Lodha)", "Sector": "Real Estate"},
    "MAFATIND.BO": {"Name": "Mafatlal Industries Ltd", "Sector": "Textiles"},
    "M&MFIN.NS": {"Name": "Mahindra & Mahindra Financial Services Ltd.", "Sector": "Financials - NBFC"},
    "MHRIL.NS": {"Name": "Mahindra Holiday", "Sector": "Hospitality"},
    "MAHLOG.NS": {"Name": "Mahindra Logis.", "Sector": "Logistics"},
    "MAITHANALL.NS": {"Name": "Maithan Alloys", "Sector": "Metals - Ferro Alloys"},
    "MANAPPURAM.NS": {"Name": "Manappuram Finance Ltd", "Sector": "Financials - NBFC"},

    "MRPL.NS": {"Name": "Mangalore Refinery & Petrochemicals Ltd.", "Sector": "Energy - Oil & Gas"},
    "MANKIND.NS": {"Name": "Mankind Pharma", "Sector": "Pharma"},
    "MARICO.NS": {"Name": "Marico", "Sector": "Consumer - FMCG"},
    "MARKSANS.NS": {"Name": "Marksans Pharma", "Sector": "Pharma"},
    "MAZDOCK.NS": {"Name": "Mazagon Dock Shipbuilders Ltd", "Sector": "Defence - Shipbuilding"},
    "MEGASTAR.NS": {"Name": "Megastar Foods", "Sector": "Consumer - Food Processing"},
    "MICEL.NS": {"Name": "MIC Electronics", "Sector": "Industrial - Electrical"},
    "MINDACORP.NS": {"Name": "Minda Corp", "Sector": "Automotive - Ancillaries"},
    "MINDSPACE.NS": {"Name": "Mindspace Business Parks REIT", "Sector": "Real Estate - REIT"},
    "MIDHANI.NS": {"Name": "Mishra Dhatu Nigam Ltd.", "Sector": "Defence - Specialty Alloys"},
    "MOSCHIP.NS": {"Name": "MosChip Technologies Ltd", "Sector": "Technology - Semiconductor"},
    "MSUMI.NS": {"Name": "Motherson Sumi Wiring India Ltd", "Sector": "Automotive - Ancillaries"},
    "MOTILALOFS.NS": {"Name": "Motilal Oswal Financial Services", "Sector": "Financials - Stockbroking"},
    "BECTORFOOD.NS": {"Name": "Mrs. Bectors Food Specialities Ltd.", "Sector": "Consumer - Food Processing"},
    "MTARTECH.NS": {"Name": "MTAR Technologies Ltd", "Sector": "Defence - Aerospace"},
    "MCX.NS": {"Name": "Multi Commodity Exchange (MCX)", "Sector": "Financials - Exchange"},
    "MUTHOOTFIN.NS": {"Name": "Muthoot Finance", "Sector": "Financials - NBFC"},
    "NDL.NS": {"Name": "Nandan Denim", "Sector": "Textiles"},
    "NATIONALUM.NS": {"Name": "National Aluminium Company", "Sector": "Metals - Non-ferrous"},
    "NFL.NS": {"Name": "National Fertilizers Ltd.", "Sector": "Chemicals - Fertilizers"},
    "NAVINFLUOR.NS": {"Name": "Navin Fluorine International Ltd.", "Sector": "Chemicals - Specialty"},
    "NCC.NS": {"Name": "NCC Ltd", "Sector": "Construction"},
    "NCLIND.NS": {"Name": "NCL Industries", "Sector": "Construction - Cement"},
    "NETWEB.NS": {"Name": "Netweb Technologies India Ltd.", "Sector": "Technology - Hardware"},
    "NEULANDLAB.NS": {"Name": "Neuland Labs.", "Sector": "Pharma - APIs"},
    "NHPC.NS": {"Name": "NHPC Ltd", "Sector": "Energy - Power"},
    "NAM-INDIA.NS": {"Name": "Nippon Life India Asset Management", "Sector": "Financials - Asset Management"},
    "NMDC.NS": {"Name": "NMDC", "Sector": "Metals - Mining"},
    "NSDL.BO": {"Name": "National Securities Depository", "Sector": "Financials - Depository"},
    "NTPC.NS": {"Name": "NTPC Ltd", "Sector": "Energy - Power"},
    "OBEROIRLTY.NS": {"Name": "Oberoi Realty", "Sector": "Real Estate"},
    "OMAXAUTO.NS": {"Name": "Omax Autos", "Sector": "Automotive - Ancillaries"},
    "PAYTM.NS": {"Name": "One 97 Communications (Paytm)", "Sector": "Financials - Fintech"},
    "ONGC.NS": {"Name": "ONGC", "Sector": "Energy - Oil & Gas"},
    "ORCHPHARMA.NS": {"Name": "Orchid Pharma", "Sector": "Pharma"},
    "ORIENTELEC.NS": {"Name": "Orient Electric", "Sector": "Consumer - Durables (Electrical)"},
    "GREENPOWER.NS": {"Name": "Orient Green Power Company Ltd.", "Sector": "Energy - Renewable"},
    "ORIENTTECH.NS": {"Name": "Orient Technologies Ltd.", "Sector": "Technology - Services"},
    "PNGJL.NS": {"Name": "P N Gadgil Jewellers", "Sector": "Retail - Jewellery"},
    "PARAS.NS": {"Name": "Paras Defence and Space Technologies Ltd.", "Sector": "Defence - Aerospace"},
    "PATELENG.NS": {"Name": "Patel Engineering Ltd.", "Sector": "Construction - Infrastructure"},
    "PERSISTENT.NS": {"Name": "Persistent.", "Sector": "Technology - Services"},
    "POLICYBZR.NS": {"Name": "PB Fintech Limited (Policybazaar)", "Sector": "Financials - Fintech"},
    "PETRONET.NS": {"Name": "Petronet LNG", "Sector": "Energy - Oil & Gas"},
    "PGEL.NS": {"Name": "PG Electroplast", "Sector": "Industrial - EMS"},
    "PHOENIXLTD.NS": {"Name": "Phoenix Mills", "Sector": "Real Estate - Retail"},
    "PIDILITIND.NS": {"Name": "Pidilite Inds.", "Sector": "Chemicals - Specialty"},
    "PPLPHARMA.NS": {"Name": "Piramal Pharma Ltd.", "Sector": "Pharma"},
    "PNCINFRA.NS": {"Name": "PNC Infratech", "Sector": "Construction - Infrastructure"},
    "POLYCAB.NS": {"Name": "Polycab India", "Sector": "Industrial - Cables"},
    "POONAWALLA.NS": {"Name": "Poonawalla Fincorp Ltd.", "Sector": "Financials - NBFC"},
    "PFC.NS": {"Name": "Power Finance Corporation Ltd.", "Sector": "Financials - NBFC"},
    "POWERGRID.NS": {"Name": "PowerGrid Corp", "Sector": "Energy - T&D"},
    "PRAJIND.NS": {"Name": "Praj Industries Ltd.", "Sector": "Industrial - Engineering"},
    "PRAKASH.NS": {"Name": "Prakash Industri", "Sector": "Metals - Steel"},
    "PREMIERENE.NS": {"Name": "Premier Energies Ltd", "Sector": "Energy - Renewable"},
    "PRESTIGE.NS": {"Name": "Prestige Estates Projects Ltd.", "Sector": "Real Estate"},
    "PRICOLLTD.NS": {"Name": "Pricol Ltd", "Sector": "Automotive - Ancillaries"},
    "PRINCEPIPE.NS": {"Name": "Prince Pipes", "Sector": "Industrial - Plastics & Pipes"},
    "PNB.NS": {"Name": "Punjab National Bank", "Sector": "Financials - Banking"},
    "PURVA.NS": {"Name": "Purvankara Ltd", "Sector": "Real Estate"},
    "PVRINOX.NS": {"Name": "PVR Inox Ltd", "Sector": "Retail - Multiplex"},
    "RADICO.NS": {"Name": "Radico Khaitan", "Sector": "Consumer - Beverages (Alcoholic)"},
    "RVNL.NS": {"Name": "Rail Vikas Nigam Limited", "Sector": "Construction - Railway"},
    "RAILTEL.NS": {"Name": "Railtel Corpn. Of India Ltd.", "Sector": "Telecom - IT"},
    "RAIN.BO": {"Name": "Rain Industries", "Sector": "Chemicals"},
    "RKFORGE.NS": {"Name": "Ramkrishna Forg.", "Sector": "Automotive - Ancillaries"},
    "RATEGAIN.NS": {"Name": "Rategain Travel Technologies Ltd.", "Sector": "Technology - Services (Travel)"},
    "RATNAMANI.NS": {"Name": "Ratnamani Metals & Tubes Ltd.", "Sector": "Metals - Steel Pipes"},
    "RTNINDIA.NS": {"Name": "RattanIndia Ent", "Sector": "Conglomerate"},
    "RTNPOWER.NS": {"Name": "RattanIndia Pow.", "Sector": "Energy - Power"},
    "RAYMONDLSL.NS": {"Name": "Raymond Lifestyle", "Sector": "Retail - Apparel"},
    "RAYMOND.NS": {"Name": "Raymond Ltd", "Sector": "Textiles - Apparel"},
    "RBLBANK.NS": {"Name": "RBL Bank Ltd.", "Sector": "Financials - Banking"},
    "RECLTD.NS": {"Name": "REC Ltd.", "Sector": "Financials - NBFC"},
    "REDINGTON.NS": {"Name": "Redington India", "Sector": "Technology - Distribution"},
    "REFEX.NS": {"Name": "Refex Industries", "Sector": "Chemicals - Specialty"},
    "RELIANCE.NS": {"Name": "Reliance Industries Ltd.", "Sector": "Conglomerate - Oil & Gas"},
    "REPCOHOME.NS": {"Name": "Repco Home Finance", "Sector": "Financials - Housing Finance"},
    "RBA.NS": {"Name": "Restaurant Brands Asia Ltd.", "Sector": "Retail - QSR"},
    "RIR.BO": {"Name": "RIR Power Electronics Ltd", "Sector": "Technology - Semiconductor"},
    "ROSSARI.NS": {"Name": "Rossari Biotech", "Sector": "Chemicals - Specialty"},
    "ROHLTD.NS": {"Name": "Royal Orch. Hotel", "Sector": "Hospitality"},
    "RUCHIRA.NS": {"Name": "Ruchira Papers", "Sector": "Paper"},
    "SHK.NS": {"Name": "S H Kelkar & Co.", "Sector": "Chemicals - Specialty"},
    "SPAL.NS": {"Name": "S P Apparels", "Sector": "Textiles - Apparel"},
    "SAGCEM.NS": {"Name": "Sagar Cements", "Sector": "Construction - Cement"},
    "SAGILITY.NS": {"Name": "Sagility India", "Sector": "Technology - Services"},
    "KALAMANDIR.NS": {"Name": "Sai Silk (Kalamandir)", "Sector": "Retail - Apparel"},
    "SAMMAANCAP.NS": {"Name": "Sammaan Capital", "Sector": "Financials - NBFC/Fintech"},
    "MOTHERSON.NS": {"Name": "Samvardhana Motherson International Ltd", "Sector": "Automotive - Ancillaries"},
    "SANSERA.NS": {"Name": "Sansera Engineering Ltd.", "Sector": "Automotive - Ancillaries"},
    "SAPPHIRE.NS": {"Name": "Sapphire Food", "Sector": "Retail - QSR"},
    "SBILIFE.NS": {"Name": "SBI Life Insurance Co Limited", "Sector": "Financials - Insurance"},
    "SCHNEIDER.NS": {"Name": "Schneider Electric Infrastructure Ltd.", "Sector": "Industrial - Electrical"},
    "SERVOTECH.NS": {"Name": "Servotech Power Systems Ltd", "Sector": "Industrial - Electrical"},
    "SGFIN.NS": {"Name": "SG Finserve Ltd.", "Sector": "Financials - NBFC"},
    "SGMART.NS": {"Name": "SG Mart Ltd.", "Sector": "Trading"},
    "SHAKTIPUMP.NS": {"Name": "Shakti Pumps", "Sector": "Industrial - Capital Goods"},
    "SCI.NS": {"Name": "Shipping Corporation Of India", "Sector": "Transport - Shipping"},
    "SHOPERSTOP.NS": {"Name": "Shoppers Stop", "Sector": "Retail - Departmental"},
    "SHRIRAMFIN.NS": {"Name": "Shriram Finance", "Sector": "Financials - NBFC"},
    "SHRIRAMPPS.NS": {"Name": "Shriram Properties", "Sector": "Real Estate"},
    "SHYAMMETL.NS": {"Name": "Shyam Metalics", "Sector": "Metals - Steel"},
    "SJS.NS": {"Name": "SJS Enterprises Ltd.", "Sector": "Automotive - Ancillaries"},
    "SJVN.NS": {"Name": "SJVN Ltd.", "Sector": "Energy - Power"},
    "SKYGOLD.NS": {"Name": "Sky Gold Limited", "Sector": "Retail - Jewellery"},
    "SILVERBEES.NS": {"Name": "Nippon India Silver ETF", "Sector": "ETF - Commodities"},
    "SOBHA.NS": {"Name": "Sobha Ltd", "Sector": "Real Estate"},
    "SOLARINDS.NS": {"Name": "Solar Industries India Ltd", "Sector": "Defence - Explosives"},
    "SOLEX.NS": {"Name": "Solex Energy Ltd", "Sector": "Energy - Renewable"},
    "SDBL.NS": {"Name": "Som Distilleries", "Sector": "Consumer - Beverages (Alcoholic)"},
    "SOMANYCERA.NS": {"Name": "Somany Ceramics", "Sector": "Construction - Materials"},
    "SOMICONVEY.NS": {"Name": "Somi Conveyor Beltings", "Sector": "Industrial - Products"},
    "SONACOMS.NS": {"Name": "Sona BLW Precision Forgings Ltd.", "Sector": "Automotive - Ancillaries"},
"SPELS.BO": {"Name": "SPEL Semiconductor Ltd", "Sector": "Technology - Semiconductor"},
    "MISHTANN.BO": {"Name": "Mishtann Foods", "Sector": "Consumer - Food Processing"},
    "MARINE.NS": {"Name": "Marine Electricals", "Sector": "Industrial - Electrical"},
    "SBC.NS": {"Name": "SBC Exports", "Sector": "Textiles"},
    "SCANPGEOM.BO": {"Name": "Scanpoint Geomatics", "Sector": "Technology - Services"},
    "RTNPOWER.NS": {"Name": "RattanIndia Power", "Sector": "Energy - Power"},
    "INA.BO": {"Name": "Insolation Energy", "Sector": "Energy - Solar", "AddedDate": "2025-04-27"},
    "GKENERGY.NS": {"Name": "GK Energy", "Sector": "Energy - Solar", "AddedDate": "2025-04-27"},
    "TUNWALSM.NS": {"Name": "Tunwal E-Motors", "Sector": "Automotive - EVs", "AddedDate": "2025-04-27"},
    "DCGSM.BO": {"Name": "DCG Cables & Wires", "Sector": "Industrial - Cables", "AddedDate": "2025-04-27"},
    "PARMESHWAR.BO": {"Name": "Parmeshwar Metal", "Sector": "Metals - Copper", "AddedDate": "2025-04-27"},
    "SHRITECH-SM.NS": {"Name": "Shri Techtex", "Sector": "Textiles - Technical", "AddedDate": "2025-04-27"},
    "PARDRGS.NS": {"Name": "Par Drugs & Chem", "Sector": "Pharma", "AddedDate": "2025-04-27"},
    "ACUTAAS.NS": {"Name": "Acutaas Chemicals", "Sector": "Chemicals - Specialty", "AddedDate": "2025-05-11"},
    "STLTECH.NS": {"Name": "STL Tech (Sterlite)", "Sector": "Technology - Optical Fibre", "AddedDate": "2025-05-11"},
    "SRF.NS": {"Name": "SRF Ltd", "Sector": "Chemicals - Specialty", "AddedDate": "2025-05-11"},
    "CLEAN.NS": {"Name": "Clean Science & Technology", "Sector": "Chemicals - Specialty", "AddedDate": "2025-05-11"},
    "WEBELSOLAR.NS": {"Name": "Websol Energy System", "Sector": "Energy - Solar", "AddedDate": "2025-05-12"},
    "YUKEN.NS": {"Name": "Yuken India", "Sector": "Industrial - Hydraulics", "AddedDate": "2025-05-12"},
    "WAA.BO": {"Name": "Waa Solar", "Sector": "Energy - Solar", "AddedDate": "2025-05-12"},
    "WINSOL-SM.NS": {"Name": "Winsol Engineers", "Sector": "Construction - Engineering", "AddedDate": "2025-05-12"},
    "WAAREEENER.NS": {"Name": "Waaree Energy", "Sector": "Energy - Solar Equipment", "AddedDate": "2025-05-12"},
}